spring.application.name=book-store
#spring.security.user.name=testUser
#spring.security.user.password=Pass1

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans
management.endpoint.health.show-details=always

EmployeeService.port=8081
EmployeeService.address=127.0.0.1

# Logging Configuration
logging.level.com.thinkconstructive.book_store=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/application.log